name: Create Pull requests on dependent components for new tag or release

# Controls when the action will run. 
on:
    push:
      tags:
        - '*'
      release:
        types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Get Current tag
      - name: 'Get Curent tag'
        id: currenttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      # React Line Style
      - name: Create Pull Request on https://github.com/Iconscout/react-unicons
        uses: akandeBolaji/change-dependency-package@v0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          package_name: unicons
          package_version: ${{ steps.currenttag.outputs.tag }}
          destination_repo: Iconscout/react-unicons
          destination_base_branch: master
          destination_head_branch: unicons-${{ steps.currenttag.outputs.tag }}-update
          user_email: tarunmangukiya@hotmail.com
          user_name: tarunmangukiya
          pull_request_reviewers: tschaefermedia
      # VueJs Line Style
      - name: Create Pull Request on https://github.com/Iconscout/vue-unicons
        uses: akandeBolaji/change-dependency-package@v0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          package_name: unicons
          package_version: ${{ steps.currenttag.outputs.tag }}
          destination_repo: Iconscout/vue-unicons
          destination_base_branch: master
          destination_head_branch: unicons-${{ steps.currenttag.outputs.tag }}-update
          user_email: tarunmangukiya@hotmail.com
          user_name: tarunmangukiya
          pull_request_reviewers: tschaefermedia
      # React Native Line Style
      - name: Create Pull Request on https://github.com/Iconscout/react-native-unicons
        uses: akandeBolaji/change-dependency-package@v0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          package_name: unicons
          package_version: ${{ steps.currenttag.outputs.tag }}
          destination_repo: Iconscout/react-native-unicons
          destination_base_branch: master
          destination_head_branch: unicons-${{ steps.currenttag.outputs.tag }}-update
          user_email: tarunmangukiya@hotmail.com
          user_name: tarunmangukiya
          pull_request_reviewers: tschaefermedia
      # React Solid Style
      - name: Create Pull Request on https://github.com/Iconscout/react-unicons-solid
        uses: akandeBolaji/change-dependency-package@v0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          package_name: unicons
          package_version: ${{ steps.currenttag.outputs.tag }}
          destination_repo: Iconscout/react-unicons-solid
          destination_base_branch: master
          destination_head_branch: unicons-${{ steps.currenttag.outputs.tag }}-update
          user_email: tarunmangukiya@hotmail.com
          user_name: tarunmangukiya
          pull_request_reviewers: tschaefermedia
      # Vue Solid Style
      - name: Create Pull Request on https://github.com/Iconscout/vue-unicons-solid
        uses: akandeBolaji/change-dependency-package@v0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          package_name: unicons
          package_version: ${{ steps.currenttag.outputs.tag }}
          destination_repo: Iconscout/vue-unicons-solid
          destination_base_branch: master
          destination_head_branch: unicons-${{ steps.currenttag.outputs.tag }}-update
          user_email: tarunmangukiya@hotmail.com
          user_name: tarunmangukiya
          pull_request_reviewers: tschaefermedia
      # React Monochrome Style
      - name: Create Pull Request on https://github.com/Iconscout/react-unicons-monochrome
        uses: akandeBolaji/change-dependency-package@v0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          package_name: unicons
          package_version: ${{ steps.currenttag.outputs.tag }}
          destination_repo: Iconscout/react-unicons-monochrome
          destination_base_branch: master
          destination_head_branch: unicons-${{ steps.currenttag.outputs.tag }}-update
          user_email: tarunmangukiya@hotmail.com
          user_name: tarunmangukiya
          pull_request_reviewers: tschaefermedia
